[source]
type = "N2C"
address = ["Unix", "/home/bakon/.cardano/testnet/socket/node.socket"]
magic = "testnet"

#[source.intersect]
#type = "Point"
#value = [22968274, "40863f0ea788421d11e06dcd985087bc447debc78bc61ca4543d6c86bf5f860b"]

[source.mapper]
include_transaction_details = true
include_block_cbor = true

[[filters]]
type = "Selection"

[filters.check]
predicate = "metadata_label_equals"
argument = "721"

[cursor]
type = "File"
path = "./cursor"

[sink]
type = "Logs"
output_path = "./new/metadata.json"
output_format = "JSONL"
max_bytes_per_file = 1_048_576
compress_files = false
